# Generated by Django 2.2.2 on 2019-11-25 01:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_friend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Follower',
        ),
    ]
